name: Build Unsigned IPA

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Unsigned IPA
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 'latest'

      - name: Fix Project Format
        run: |
          sed -i '' 's/objectVersion = 77/objectVersion = 56/' dirtyZero.xcodeproj/project.pbxproj
          sed -i '' 's/preferredProjectObjectVersion = 77/preferredProjectObjectVersion = 56/' dirtyZero.xcodeproj/project.pbxproj
          
      - name: Additional Project Format Fixes
        run: |
          plutil -convert xml1 dirtyZero.xcodeproj/project.pbxproj
          
      - name: Prepare C File
        run: |
          xcodebuild -project dirtyZero.xcodeproj -target dirtyZero -showBuildSettings
          
      - name: Archive Build (Unsigned)
        run: |
          xcodebuild clean archive \
            -project dirtyZero.xcodeproj \
            -scheme "dirtyZero" \
            -configuration Release \
            -archivePath build/dirtyZero.xcarchive \
            -sdk iphoneos \
            -destination 'generic/platform=iOS' \
            ONLY_ACTIVE_ARCH=NO \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            SWIFT_OPTIMIZATION_LEVEL="-Onone" \
            IPHONEOS_DEPLOYMENT_TARGET=16.0
            
      - name: Create IPA from Archive
        run: |
          cp -R build/dirtyZero.xcarchive/Products/Applications/dirtyZero.app .
          mkdir -p Payload
          cp -R dirtyZero.app Payload/
          zip -r dirtyZero.ipa Payload
          rm -rf Payload dirtyZero.app
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: dirtyZero.ipa
          path: dirtyZero.ipa
          retention-days: 90
